sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
script:
  - npm run test
  - npm run test:func
branches:
  only:
    - master
